package testAES;



public class Main extends javax.swing.JFrame {
	 /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private byte[] encrypted;


	    public Main() {
	    	 initComponents();
	    	 
	         setTitle("DEMO AES by Nhóm 3 _NHẬP MÔN AN TOÀN THÔNG TIN");
	         setLocationRelativeTo(null);
	    }

	    /**
	     * This method is called from within the constructor to initialize the form.
	     * WARNING: Do NOT modify this code. The content of this method is always
	     * regenerated by the Form Editor.
	     */
	    
	    private void initComponents() {

	        jPanel1 = new javax.swing.JPanel();
	        jLabel1 = new javax.swing.JLabel();
	        jLabel2 = new javax.swing.JLabel();
	        txtNDMaHoa = new javax.swing.JTextField();
	        jLabel3 = new javax.swing.JLabel();
	        txtKeyMaHoa = new javax.swing.JTextField();
	        jLabel4 = new javax.swing.JLabel();
	        txtNDSauMH = new javax.swing.JTextField();
	        jLabel5 = new javax.swing.JLabel();
	        jLabel6 = new javax.swing.JLabel();
	        jLabel7 = new javax.swing.JLabel();
	        jLabel8 = new javax.swing.JLabel();
	        txtNDSauGiaiKhoa = new javax.swing.JTextField();
	        txtNDGiaiKhoa = new javax.swing.JTextField();
	        txtKeyGiaiKhoa = new javax.swing.JTextField();
	        btnMaHoa = new javax.swing.JButton();
	        btnXoaTrangMa = new javax.swing.JButton();
	        btnGiaiKhoa = new javax.swing.JButton();
	        btnClear = new javax.swing.JButton();
	        jButton1 = new javax.swing.JButton();

	        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

	        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

	        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
	        jLabel1.setText("Mã hóa với thuật toán AES");

	        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
	        jLabel2.setText("Plain Text:");

	        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
	        jLabel3.setText("Key to Encrypted: ");

	        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
	        jLabel4.setText("Encrypted:");

	        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
	        jLabel5.setText("Giải mã với thuật toán AES");

	        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
	        jLabel6.setText("Plain Text:");

	        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
	        jLabel7.setText("Key to Decrypted:");

	        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
	        jLabel8.setText("Decrypted:");

	        btnMaHoa.setText("Encrypted code:");
	        btnMaHoa.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	                btnMaHoaActionPerformed(evt);
	            }
	        });

	        btnXoaTrangMa.setText("Clear");
	        btnXoaTrangMa.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	                btnXoaTrangMaActionPerformed(evt);
	            }
	        });

	        btnGiaiKhoa.setText("Decrypted code");
	        btnGiaiKhoa.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	                btnGiaiKhoaActionPerformed(evt);
	            }
	        });

	        btnClear.setText("Clear");
	        btnClear.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	                btnClearActionPerformed(evt);
	            }
	        });
	       
	        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
	        jPanel1.setLayout(jPanel1Layout);
	        jPanel1Layout.setHorizontalGroup(
	            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	            .addGroup(jPanel1Layout.createSequentialGroup()
	                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	                    .addGroup(jPanel1Layout.createSequentialGroup()
	                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	                            .addGroup(jPanel1Layout.createSequentialGroup()
	                                .addGap(23, 23, 23)
	                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
	                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
	                                    .addComponent(jLabel4)
	                                    .addGroup(jPanel1Layout.createSequentialGroup()
	                                        .addGap(8, 8, 8)
	                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	                                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
	                                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
	                                            .addComponent(jLabel8)))))
	                            .addGroup(jPanel1Layout.createSequentialGroup()
	                                .addContainerGap()
	                                .addComponent(jButton1)))
	                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	                            .addGroup(jPanel1Layout.createSequentialGroup()
	                                .addGap(58, 58, 58)
	                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	                                    .addComponent(txtKeyGiaiKhoa, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE)
	                                    .addComponent(txtNDGiaiKhoa, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE)
	                                    .addComponent(txtNDSauGiaiKhoa, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE)
	                                    .addGroup(jPanel1Layout.createSequentialGroup()
	                                        .addComponent(btnGiaiKhoa, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
	                                        .addGap(200, 200, 200)
	                                        .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))))
	                            .addGroup(jPanel1Layout.createSequentialGroup()
	                                .addGap(133, 133, 133)
	                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE))
	                            .addGroup(jPanel1Layout.createSequentialGroup()
	                                .addGap(50, 50, 50)
	                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	                                    .addGroup(jPanel1Layout.createSequentialGroup()
	                                        .addGap(10, 10, 10)
	                                        .addComponent(btnMaHoa, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
	                                        .addGap(183, 183, 183)
	                                        .addComponent(btnXoaTrangMa, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
	                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
	                                        .addComponent(txtNDMaHoa)
	                                        .addComponent(txtKeyMaHoa)
	                                        .addComponent(txtNDSauMH, javax.swing.GroupLayout.DEFAULT_SIZE, 462, Short.MAX_VALUE))))))
	                    .addGroup(jPanel1Layout.createSequentialGroup()
	                        .addGap(361, 361, 361)
	                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)))
	                .addContainerGap(183, Short.MAX_VALUE))
	        );
	        jPanel1Layout.setVerticalGroup(
	            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	            .addGroup(jPanel1Layout.createSequentialGroup()
	                .addContainerGap()
	                .addComponent(jLabel1)
	                .addGap(21, 21, 21)
	                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
	                    .addComponent(txtNDMaHoa, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
	                    .addComponent(jLabel2))
	                .addGap(18, 18, 18)
	                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
	                    .addComponent(jLabel3)
	                    .addComponent(txtKeyMaHoa, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
	                .addGap(22, 22, 22)
	                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
	                    .addComponent(txtNDSauMH, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
	                    .addComponent(jLabel4))
	                .addGap(18, 18, 18)
	                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
	                    .addComponent(btnMaHoa, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
	                    .addComponent(btnXoaTrangMa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
	                .addGap(50, 50, 50)
	                .addComponent(jLabel5)
	                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
	                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
	                    .addComponent(txtNDGiaiKhoa, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
	                    .addComponent(jLabel6))
	                .addGap(24, 24, 24)
	                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
	                    .addComponent(jLabel7)
	                    .addComponent(txtKeyGiaiKhoa, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
	                .addGap(21, 21, 21)
	                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
	                    .addComponent(jLabel8)
	                    .addComponent(txtNDSauGiaiKhoa, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
	                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	                    .addGroup(jPanel1Layout.createSequentialGroup()
	                        .addGap(26, 26, 26)
	                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
	                            .addComponent(btnGiaiKhoa, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
	                            .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
	                        .addGap(40, 40, 40))
	                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
	                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
	                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
	                        .addContainerGap())))
	        );

	        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
	        getContentPane().setLayout(layout);
	        layout.setHorizontalGroup(
	            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
	        );
	        layout.setVerticalGroup(
	            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
	        );

	        pack();
	    }// </editor-fold>//GEN-END:initComponents

	

		private void btnMaHoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMaHoaActionPerformed
	        String mes =  txtNDMaHoa.getText();
	        String key = txtKeyMaHoa.getText();
	        encrypted = AES.encryptECB(mes.getBytes(), key.getBytes());
	       txtNDSauMH.setText(new String(encrypted));
	    }//GEN-LAST:event_btnMaHoaActionPerformed

	    private void btnXoaTrangMaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaTrangMaActionPerformed
	        txtKeyMaHoa.setText("");
	        txtNDMaHoa.setText("");
	        txtNDSauMH.setText("");
	    }//GEN-LAST:event_btnXoaTrangMaActionPerformed

	    private void btnGiaiKhoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGiaiKhoaActionPerformed
	      //String message =  txtNDGiaiKhoa.getText();
	      String key = txtKeyGiaiKhoa.getText();
	      byte[] decrypted = AES.decryptECB(encrypted, key.getBytes());
	      txtNDSauGiaiKhoa.setText(new String(decrypted));
	    }//GEN-LAST:event_btnGiaiKhoaActionPerformed

	    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
	        txtKeyGiaiKhoa.setText("");
	        txtNDGiaiKhoa.setText("");
	        txtNDSauGiaiKhoa.setText("");
	    }//GEN-LAST:event_btnClearActionPerformed
	   
	    

	    /**
	     * @param args the command line arguments
	     */
	    public static void main(String args[])  throws  Exception{
	        try {
	            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
	                if ("Nimbus".equals(info.getName())) {
	                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
	                    break;
	                }
	            }
	        } catch (ClassNotFoundException ex) {
	            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	        } catch (InstantiationException ex) {
	            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	        } catch (IllegalAccessException ex) {
	            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
	            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	        }
	        //</editor-fold>

	        /* Create and display the form */
	        java.awt.EventQueue.invokeLater(new Runnable() {
	            public void run() {
	                new Main().setVisible(true);
	            }
	        });
	    }

	    // Variables declaration - do not modify//GEN-BEGIN:variables
	    private javax.swing.JButton btnClear;
	    private javax.swing.JButton btnGiaiKhoa;
	    private javax.swing.JButton btnMaHoa;
	    private javax.swing.JButton btnXoaTrangMa;
	    private javax.swing.JButton jButton1;
	    private javax.swing.JLabel jLabel1;
	    private javax.swing.JLabel jLabel2;
	    private javax.swing.JLabel jLabel3;
	    private javax.swing.JLabel jLabel4;
	    private javax.swing.JLabel jLabel5;
	    private javax.swing.JLabel jLabel6;
	    private javax.swing.JLabel jLabel7;
	    private javax.swing.JLabel jLabel8;
	    private javax.swing.JPanel jPanel1;
	    private javax.swing.JTextField txtKeyGiaiKhoa;
	    private javax.swing.JTextField txtKeyMaHoa;
	    private javax.swing.JTextField txtNDGiaiKhoa;
	    private javax.swing.JTextField txtNDMaHoa;
	    private javax.swing.JTextField txtNDSauGiaiKhoa;
	    private javax.swing.JTextField txtNDSauMH;
	    // End of variables declaration//GEN-END:variables
}
